chore(prisma): add seed
paastech-cloud/api pull request #15
Opened 2023-07-05 22:28 UTC by Martin-Moreira-de-jesus

## What does this do ?

This adds a [seed](https://www.prisma.io/docs/guides/migrate/seed-database) purely meant for development purposes.
Read the comment in the prisma/seed.ts for more information.

## How do I test it ?

Add the `DEV_USER_PASSWORD` environment variable to your `.env` file and then run the following command :

```bash
npx prisma db seed
```

For more information, consult README.md

Finally, you can at the data added. Note that it can be run multiple times.

2023-07-06 07:31 UTC, BioTheWolff requested changes
Looking good so far, I suggest improving by loading directly from a ssh public key file given by the user

2023-07-06 07:31 UTC, BioTheWolff commented on .env.example
> +DEV_USER_PASSWORD=PaastechDev1!
I suggest adding a way to load the public ssh key from a given location, so it can get easier to run.

```suggestion
DEV_USER_PASSWORD=PaastechDev1!
DEV_USER_SSH_PUBKEY_FILE=/my/dev/ssh/keyfile
```

2023-07-06 07:31 UTC, BioTheWolff commented on prisma/seed.ts
> +
Use `readFileSync` to read the SSH keyfile

```suggestion
import { readFileSync } from 'fs';

```

2023-07-06 07:31 UTC, BioTheWolff commented on prisma/seed.ts
> +          value: 'PUT YOUR PUBLIC SSH KEY HERE',
```suggestion
          value: sshKey,
```

2023-07-06 07:31 UTC, BioTheWolff commented on prisma/seed.ts
> +          value: 'PUT YOUR PUBLIC SSH KEY HERE',
```suggestion
          value: sshKey,
```

2023-07-06 20:44 UTC, Martin-Moreira-de-jesus commented
@BioTheWolff Why not just use environment variables ? Just like I did for the password ? The user would generate a keypair and add the public key in the .env file.

2023-07-06 21:01 UTC, BioTheWolff commented
> @BioTheWolff Why not just use environment variables ? Just like I did for the password ? The user would generate a keypair and add the public key in the .env file.

`.env` files do not support multi-line values, and SSH keys require to be multi-line as the line returns are necessary. Hence the suggestion for an env variable redirecting to a keyfile

2023-07-08 16:19 UTC, BioTheWolff approved these changes
Looks good to me!

2023-07-09 10:13 UTC, thomas-mauran approved these changes

2023-07-09 10:14 UTC, merged