Add Swagger response decorator to every endpoint
paastech-cloud/api pull request #24
Opened 2023-07-11 10:02 UTC by sea-gull-diana

This PR adds Swagger response decorators (`@ApiResponse`, `@ApiOkResponse`, etc.) directly to routes, since adding them just at the beginning of a Controller is not enough (it only sets a default response type, not the main one, which is still deduced by CLI plugin as an empty object).

Since website autogenerates request functions based on the openapi spec given by NestJS, it is useful to have a clearly defined response type. If somebody finds out a way to do it without manually adding a decorator to each route, that would be great :)

2023-07-11 10:24 UTC, lapsus-ord submitted a review, later dismissed

2023-07-11 13:47 UTC, BioTheWolff requested changes
Looking very good, thanks for the PR! Just a few corrections needed on things you already have applied elsewhere; I think it's just things that have been forgotten and it's alright!

2023-07-11 13:47 UTC, BioTheWolff commented on src/auth/auth.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
This could be an `@ApiCreatedResponse` like the method under!

2023-07-11 13:47 UTC, BioTheWolff commented on src/auth/auth.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
Same for this, could be `@ApiCreatedResponse`

2023-07-11 13:47 UTC, BioTheWolff commented on src/auth/auth.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
Same again

2023-07-11 13:47 UTC, BioTheWolff commented on src/auth/auth.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
Another one!

2023-07-11 13:47 UTC, BioTheWolff commented on src/projects/projects.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
This could be an `@ApiCreatedResponse`

2023-07-11 13:47 UTC, BioTheWolff commented on src/projects/projects.controller.ts
> +  @ApiResponse({ status: 201, type: ApiStandardResponse })
Same here

2023-07-12 10:21 UTC, BioTheWolff approved these changes
LGTM!

2023-07-12 10:22 UTC, thomas-mauran approved these changes

2023-07-12 10:23 UTC, merged